### ISSUE TITLE
feature: poolable messages paths with wildcard

### ISSUE THREAD

**Issue by evgfedotov** [planetscale/vtprotobuf#114]
There are currently two ways to define messages to which the "pool" functionality will be applied:

1. Via per-message option`vtproto.mempool`
2. By enumerating messages with the `pool` flag

Both of these methods don't work well for large numbers of messages. 

It might be worth adding the ability to use wildcards in `pool` flag to determine group of messages.

For example in my existing buf configuration:

```yaml
version: v1
plugins:
    - name: go-vtproto
      path: bin/protoc-gen-go-vtproto
      out: .
      opt:
        - features=marshal+unmarshal+size+pool+grpc
        - paths=source_relative
        - pool=github.com/some/api/example1.Message1
        - pool=github.com/some/api/example2.Message2
        - pool=...
        - pool=github.com/some/api/example3.Message100
      strategy: directory
```

Instead could be:

```yaml
version: v1
plugins:
    - name: go-vtproto
      path: bin/protoc-gen-go-vtproto
      out: .
      opt:
        - features=marshal+unmarshal+size+pool+grpc
        - paths=source_relative
        - pool=github.com/some/service/api/*
      strategy: directory
```

For more flexibility it is also possible to add a flag to exclude some messages from `pool` feature generation.
