### ISSUE TITLE
How to generate pool methods from buf cli

### ISSUE THREAD

**Issue by johnsiilver** [planetscale/vtprotobuf#85]
So I've got a slightly different method of generating protobufs.  I used the buf cli to generate protos and my config file looks like the following:

```yaml
version: v1
plugins:
  - name: go
    out: ./generated/
    opt: paths=source_relative
  - plugin: buf.build/grpc/go:v1.3.0
    out: ./
    opt:
      - paths=source_relative
  - plugin: go-vtproto
    out: ./
    opt:
      - paths=source_relative
      - features=marshal+unmarshal+size+equal+pool+clone
 ```

I have both used and not used `features`, which ends up having the same outcome.  None of the pool methods are generated on the types, such as `ReturnToVTPool` or `ResetVT`.  All other methods are generated.

I'm using the latest version of the plugin.

I noticed that in a bug, someone was doing:

```proto
message Parent {
  option (vtproto.mempool) = true;
  repeated Child children = 1;
  Child one = 2;
}

message Child {
  option (vtproto.mempool) = true;
  uint32 field = 1;
}
```

with `option (vtproto.mempool) = true;`

This didn't work for me, giving an error about an unsupported option.  Also, the only reference I found was in the bug, I never saw it in regular documentation.  

I'm sure I'm missing something simple, but not sure what it is.  Any help would be appreciated.  And thanks for the hard work on this project.  We certainly needed something to take up the slack with gogoproto being deprecated.
